# Generated by Django 3.2.4 on 2022-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_modulo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
