# Generated by Django 3.2.4 on 2022-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='publico',
            field=models.TextField(null=True),
        ),
    ]
