# Generated by Django 3.2.4 on 2022-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_alter_aula_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
